### ISSUE TITLE
Percent Change Dashboards

### ISSUE THREAD

**Issue by chand1012** [multisig-labs/ceres#18]
There will be 2 dashboard.
- Percent growth of the last week
- Percent growth of the last month

Both will use Grafana Dashboards and Grafana Reporting. Generate the percent change of each item on the [dashboard](https://dash.gogopool.com). Copy the dashboard and make them that way.

**Comment by gatesyp** [comment]
SG needs growth stats - TVL growth, minipool growth, liquid staking growth. maaybe effectiveGGPStake growth @Chandler (make new panel that shows % change over last month / week) (probably early next week)
