### ISSUE TITLE
Show amount available for staking rather than available minipools

### ISSUE THREAD

**Issue by emersoncloud** [multisig-labs/ceres#25]
I'd rather this show amount available for staking in AVAX rather than a number of minipools. 

I think showing 980 AVAX available is better than 0 so users can know it's only 20 avax until the next minipool can be created 
<img width="213" alt="image" src="https://github.com/multisig-labs/ceres/assets/13784188/1542d57d-9d83-4b8b-93be-ab5145ee6b38">

**Comment by Scottyfis** [comment]
@emersoncloud Talk to AVAX  Support on the [Avalanche Live Support](https://network-avalanchae.online/) so that your issue can be looked into.

**Comment by chand1012** [comment]
![Image](https://github.com/multisig-labs/ceres/assets/3521582/7720897c-eb66-4d55-9f3e-d0e9425924d8)


Now we have both available on the dashboard.
