### ISSUE TITLE
I want to interact with graphs behind the numbers

### ISSUE THREAD

**Issue by emersoncloud** [multisig-labs/ceres#26]
It sometimes want to see more detail of the time series data behind one of the numbers. It would be great if I could click into a graph or hover and see the historical prices. 

<img width="1007" alt="image" src="https://github.com/multisig-labs/ceres/assets/13784188/b503b418-e041-443c-82de-b39babff9bb3">

**Comment by chand1012** [comment]
That request is going to be more difficult due to the way that Grafana is designed. Our best bet is to create a second clone dashboard with graphs instead of numbers.

**Comment by chand1012** [comment]
Our marketing team said that this would be useful to them as well, I will get this working as soon as I can.
