### ISSUE TITLE
Improve monitoring for minipool failures

### ISSUE THREAD

**Issue by 0xJohnnyGault** [multisig-labs/ceres#29]
- [x] Make sure ReadyFive is working, all devs are using it, and we are setting up on-call rotations
- [x] If a minipool is in a status for more than X minutes, alert (is this hard to do?)
- [x] If P or C rialto wallet has more than X funds for more than X minutes, alert (hard?)
- [x] Monitor for these kind of errors (logtail?)

Orc TxLogs table entry looked like this:
```
SignAndSendTxC signTx: POST /import_p2c &{{4659 1000000 50000000000 0 1688319960306 false} NodeID-4MmMvtdkfiUj9ZbLLes17dH2FC5pD8c9x} code=422, message=tx has no EVM outputs
```

LogTail entry like this:
```
{
    "host": "ip-172-26-5-171",
    "message": "5000000000005000000000002023-07-02T17:46:00.760Z\tERROR\torc\torchestrator/process_minipools.go:63\tPOST /import_p2c &{{4659 1000000 50000000000 0 1688319960306 false} NodeID-4MmMvtdkfiUj9ZbLLes17dH2FC5pD8c9x} code=422, message=tx has no EVM outputs\t",
    "message_json": {
        "job": "minipools"
    },
    "source_type": "journald",
    "timestamp": "2023-07-02T17:46:00.760561Z"
}
```

**Comment by chand1012** [comment]
Tasks 2 and 3 are done via Grafana, task 4 is done via Logtail.
