### ISSUE TITLE
GGP Circulating Supply API

### ISSUE THREAD

**Issue by 0xju1ie** [multisig-labs/ceres#32]
Research requirements for CoinGecko, DefiLlama, CoinMarketCap, and make an API for it.

Possibly just use a protocol variable in Storage? Or host a small api on Coolify or serverless func Cloudflare?

**Comment by 0xju1ie** [comment]
https://accounts.google.com/v3/signin/confirmidentifier?authuser=2&continue=https://docs.google.com/spreadsheets/u/2/d/1tuqqxX6E2m6He7zzlr3qnYnQmZXIkYvpoe6dCs8SroI/edit?pli%3D1&followup=https://docs.google.com/spreadsheets/u/2/d/1tuqqxX6E2m6He7zzlr3qnYnQmZXIkYvpoe6dCs8SroI/edit?pli%3D1&ifkv=AeDOFXi0jhUdg8tWxhcvTzfujVRJg1rijJHnHkw19w1X6R3oASjoFjdNAkaUXZi2wUJT7iRUr7IIHA&ltmpl=sheets&osid=1&passive=1209600&service=wise&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S1242045799:1690999809646014#gid=743142986

https://docs.google.com/spreadsheets/d/12HmOFNzPSjFiTxORnrOEtZTBeiHQpbxfTzobl_YK-EI/edit#gid=0

https://docs.google.com/spreadsheets/d/1tuqqxX6E2m6He7zzlr3qnYnQmZXIkYvpoe6dCs8SroI/edit?pli=1#gid=1975429735

**Comment by chand1012** [comment]
Closed (again) via #36

**Comment by 0xju1ie** [comment]
coingecko spreadsheet is done, and I submitted a request to coingecko: 
https://support.coingecko.com/hc/en-us/articles/8820830357017-How-do-I-update-token-info-on-CoinGecko-token-page-#:~:text=Login%20into%20your%20CoinGecko%20account,Update%20Coin%2FToken%20listing%E2%80%9D

https://support.coingecko.com/hc/en-us/articles/9510930080921-How-do-I-fill-out-the-Tokenomics-Disclosure-Sheet-on-CoinGecko-

https://support.coingecko.com/hc/en-us/requests/new?ticket_form_id=4473384680089

https://docs.google.com/spreadsheets/d/1tuqqxX6E2m6He7zzlr3qnYnQmZXIkYvpoe6dCs8SroI/edit?pli=1#gid=743142986

**Comment by 0xju1ie** [comment]
need to look into defilama and coinmarketcap

oh and these are the newly added endpoints to ceres:
ceres.gogopool.com/ggpCirculatingSupply
ceres.gogopool.com/ggpTotalSupply (as defined by coingecko)
